name: Create release pull request

on:
  workflow_dispatch:
    inputs:
      newVersionNumber:
        description: 'New version number'
        required: true

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Replace version
        run: |
          sed -i -e '/version =/ s/= .*/= ${{ github.event.inputs.newVersionNumber }}/' ./plugins/sqlfluff-templater-dbt/setup.cfg
          sed -i -e '/version =/ s/= .*/= ${{ github.event.inputs.newVersionNumber }}/' ./setup.cfg
          sed -i -e '/stable_version =/ s/= .*/= ${{ github.event.inputs.newVersionNumber }}/' ./setup.cfg

      - name: Start Changelog entry
        run: |
          function dt {
            date +'%Y-%m-%d'
          }
          sed -i "s/<!--Start Of Releases (DO NOT DELETE THIS LINE)-->/<!--Start Of Releases (DO NOT DELETE THIS LINE)-->\n\n## [${{ github.event.inputs.newVersionNumber }}] - $(date +%F)\n\n## Highlights\n\n## What’s Changed\n\n## New Contributors/" ./CHANGELOG.md

      - name: Create pull request
        uses: peter-evans/create-pull-request@v4
        with:
          delete-branch: true
          branch: prep-${{ github.event.inputs.newVersionNumber }}
          branch-suffix: short-commit-hash
          commit-message: "Bump to version ${{ github.event.inputs.newVersionNumber }}"
          title: Prep version ${{ github.event.inputs.newVersionNumber }}
          body: |
            Prepare version ${{ github.event.inputs.newVersionNumber }}

            Please add all merged changes from [Release Draft][1] to
            the CHANGELOG.md file

            - Auto-generated by [create-pull-request][2] GitHub Action

            [1]: https://github.com/sqlfluff/sqlfluff/releases
            [2]: https://github.com/peter-evans/create-pull-request
          labels: release
