###########################
## Linter GitHub Actions ##
###########################
#
# This uses a collection of linters in one convienent package to avoid
# installing lots of languages and dependencies
#
# We still do our main Python linting in the other checks since we already
# have python dependencies and it's working well for us there.
#
# Documentation: https://github.com/github/super-linter/
#
# Exception config files are in the .github/linters directory
#
name: Lint Code Base
on:
  - workflow_dispatch
  - pull_request
jobs:
  lint:
    name: Lint Code Base
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0
      - name: Set VALIDATE_ALL_CODEBASE variable to false
        # Only run the full workflow for manual runs or if upgrading the super linter
        if: |
            github.event_name != 'workflow_dispatch' &&
            startsWith(github.event.pull_request.title,'Bump github/super-linter') != true
        run: |
          echo "ALIDATE_ALL_CODEBASE=false" >> $GITHUB_ENV
      - name: Lint Code Base
        uses: github/super-linter@v4
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_CSS: true
          VALIDATE_JSON: true
          VALIDATE_MD: true
          VALIDATE_ALL_CODEBASE: true
